In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

In [2]:
ls

 Volume in drive C has no label.
 Volume Serial Number is 4CEF-E2B2

 Directory of C:\Users\HP\Documents\Assignment questions\Logistic Regression

12-05-2023  06:58    <DIR>          .
25-04-2023  21:22    <DIR>          ..
12-05-2023  06:56    <DIR>          .ipynb_checkpoints
09-04-2023  14:30             2,436 50_Startups.csv
09-04-2023  14:32         4,610,348 bank-full.csv
09-04-2023  14:32               108 Problem-Statement(Bank_data).txt
12-05-2023  06:58             1,072 Untitled.ipynb
               4 File(s)      4,613,964 bytes
               3 Dir(s)  423,957,880,832 bytes free


In [6]:
dataset=pd.read_csv("bank-full.csv",sep=";")

In [7]:
dataset.head()

age           job  marital  education default  balance housing loan  \
0   58    management  married   tertiary      no     2143     yes   no   
1   44    technician   single  secondary      no       29     yes   no   
2   33  entrepreneur  married  secondary      no        2     yes  yes   
3   47   blue-collar  married    unknown      no     1506     yes   no   
4   33       unknown   single    unknown      no        1      no   no   

   contact  day month  duration  campaign  pdays  previous poutcome   y  
0  unknown    5   may       261         1     -1         0  unknown  no  
1  unknown    5   may       151         1     -1         0  unknown  no  
2  unknown    5   may        76         1     -1         0  unknown  no  
3  unknown    5   may        92         1     -1         0  unknown  no  
4  unknown    5   may       198         1     -1         0  unknown  no

In [9]:
dataset["y"].value_counts()

no     39922
yes     5289
Name: y, dtype: int64

In [10]:
dataset.isna().sum()

age          0
job          0
marital      0
education    0
default      0
balance      0
housing      0
loan         0
contact      0
day          0
month        0
duration     0
campaign     0
pdays        0
previous     0
poutcome     0
y            0
dtype: int64

In [12]:
dataset.columns

Index(['age', 'job', 'marital', 'education', 'default', 'balance', 'housing',
       'loan', 'contact', 'day', 'month', 'duration', 'campaign', 'pdays',
       'previous', 'poutcome', 'y'],
      dtype='object')

In [13]:
dataset.y.replace(to_replace=["no","yes"],value=[0,1],inplace=True)

In [16]:
dataset["y"].value_counts()

0    39922
1     5289
Name: y, dtype: int64

In [17]:
dataset = dataset[['y','age', 'job', 'marital', 'education', 'default', 'balance', 'housing',
       'loan', 'contact', 'day', 'month','duration','campaign', 'pdays',
       'previous', 'poutcome']]

In [18]:
dataset

y  age           job   marital  education default  balance housing  \
0      0   58    management   married   tertiary      no     2143     yes   
1      0   44    technician    single  secondary      no       29     yes   
2      0   33  entrepreneur   married  secondary      no        2     yes   
3      0   47   blue-collar   married    unknown      no     1506     yes   
4      0   33       unknown    single    unknown      no        1      no   
...   ..  ...           ...       ...        ...     ...      ...     ...   
45206  1   51    technician   married   tertiary      no      825      no   
45207  1   71       retired  divorced    primary      no     1729      no   
45208  1   72       retired   married  secondary      no     5715      no   
45209  0   57   blue-collar   married  secondary      no      668      no   
45210  0   37  entrepreneur   married  secondary      no     2971      no   

      loan    contact  day month  duration  campaign  pdays  previous poutcome  
0       no    unknown    5   may       261         1     -1         0  unknown  
1       no    unknown    5   may       151         1     -1         0  unknown  
2      yes    unknown    5   may        76         1     -1         0  unknown  
3       no    unknown    5   may        92         1     -1         0  unknown  
4       no    unknown    5   may       198         1     -1         0  unknown  
...    ...        ...  ...   ...       ...       ...    ...       ...      ...  
45206   no   cellular   17   nov       977         3     -1         0  unknown  
45207   no   cellular   17   nov       456         2     -1         0  unknown  
45208   no   cellular   17   nov      1127         5    184         3  success  
45209   no  telephone   17   nov       508         4     -1         0  unknown  
45210   no   cellular   17   nov       361         2    188        11    other  

[45211 rows x 17 columns]

In [19]:
dataset.head()

y  age           job  marital  education default  balance housing loan  \
0  0   58    management  married   tertiary      no     2143     yes   no   
1  0   44    technician   single  secondary      no       29     yes   no   
2  0   33  entrepreneur  married  secondary      no        2     yes  yes   
3  0   47   blue-collar  married    unknown      no     1506     yes   no   
4  0   33       unknown   single    unknown      no        1      no   no   

   contact  day month  duration  campaign  pdays  previous poutcome  
0  unknown    5   may       261         1     -1         0  unknown  
1  unknown    5   may       151         1     -1         0  unknown  
2  unknown    5   may        76         1     -1         0  unknown  
3  unknown    5   may        92         1     -1         0  unknown  
4  unknown    5   may       198         1     -1         0  unknown

In [20]:
data1=pd.get_dummies(dataset,columns=['job', 'marital', 'education', 'default', 'housing','loan', 'contact','month', 'poutcome'])

In [21]:
data1.head()

y  age  balance  day  duration  campaign  pdays  previous  job_admin.  \
0  0   58     2143    5       261         1     -1         0           0   
1  0   44       29    5       151         1     -1         0           0   
2  0   33        2    5        76         1     -1         0           0   
3  0   47     1506    5        92         1     -1         0           0   
4  0   33        1    5       198         1     -1         0           0   

   job_blue-collar  ...  month_jun  month_mar  month_may  month_nov  \
0                0  ...          0          0          1          0   
1                0  ...          0          0          1          0   
2                0  ...          0          0          1          0   
3                1  ...          0          0          1          0   
4                0  ...          0          0          1          0   

   month_oct  month_sep  poutcome_failure  poutcome_other  poutcome_success  \
0          0          0                 0               0                 0   
1          0          0                 0               0                 0   
2          0          0                 0               0                 0   
3          0          0                 0               0                 0   
4          0          0                 0               0                 0   

   poutcome_unknown  
0                 1  
1                 1  
2                 1  
3                 1  
4                 1  

[5 rows x 52 columns]

In [22]:

#model building

In [26]:
#independent and dependent variables
x = data1.iloc[:,1::]

In [27]:
y=data1.iloc[:,0]

In [28]:
x

age  balance  day  duration  campaign  pdays  previous  job_admin.  \
0       58     2143    5       261         1     -1         0           0   
1       44       29    5       151         1     -1         0           0   
2       33        2    5        76         1     -1         0           0   
3       47     1506    5        92         1     -1         0           0   
4       33        1    5       198         1     -1         0           0   
...    ...      ...  ...       ...       ...    ...       ...         ...   
45206   51      825   17       977         3     -1         0           0   
45207   71     1729   17       456         2     -1         0           0   
45208   72     5715   17      1127         5    184         3           0   
45209   57      668   17       508         4     -1         0           0   
45210   37     2971   17       361         2    188        11           0   

       job_blue-collar  job_entrepreneur  ...  month_jun  month_mar  \
0                    0                 0  ...          0          0   
1                    0                 0  ...          0          0   
2                    0                 1  ...          0          0   
3                    1                 0  ...          0          0   
4                    0                 0  ...          0          0   
...                ...               ...  ...        ...        ...   
45206                0                 0  ...          0          0   
45207                0                 0  ...          0          0   
45208                0                 0  ...          0          0   
45209                1                 0  ...          0          0   
45210                0                 1  ...          0          0   

       month_may  month_nov  month_oct  month_sep  poutcome_failure  \
0              1          0          0          0                 0   
1              1          0          0          0                 0   
2              1          0          0          0                 0   
3              1          0          0          0                 0   
4              1          0          0          0                 0   
...          ...        ...        ...        ...               ...   
45206          0          1          0          0                 0   
45207          0          1          0          0                 0   
45208          0          1          0          0                 0   
45209          0          1          0          0                 0   
45210          0          1          0          0                 0   

       poutcome_other  poutcome_success  poutcome_unknown  
0                   0                 0                 1  
1                   0                 0                 1  
2                   0                 0                 1  
3                   0                 0                 1  
4                   0                 0                 1  
...               ...               ...               ...  
45206               0                 0                 1  
45207               0                 0                 1  
45208               0                 1                 0  
45209               0                 0                 1  
45210               1                 0                 0  

[45211 rows x 51 columns]

In [29]:
y

0        0
1        0
2        0
3        0
4        0
        ..
45206    1
45207    1
45208    1
45209    0
45210    0
Name: y, Length: 45211, dtype: int64

In [32]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
from sklearn import preprocessing
from sklearn import metrics

In [33]:
model=LogisticRegression(random_state=0)
model.fit(x,y)

LogisticRegression(random_state=0)

In [34]:
model.intercept_

array([-0.27756233])

In [35]:
np.round(model.coef_,2)

array([[-0.02,  0.  , -0.01,  0.  , -0.39,  0.  , -0.11, -0.03, -0.25,
        -0.03, -0.01,  0.01,  0.16, -0.02, -0.09,  0.03, -0.07,  0.  ,
         0.  ,  0.02, -0.17, -0.12, -0.07, -0.27,  0.05,  0.01, -0.26,
        -0.02,  0.36, -0.63, -0.08, -0.2 ,  0.09,  0.05, -0.42,  0.04,
         0.02,  0.03, -0.01, -0.01, -0.08, -0.06,  0.09, -0.4 , -0.06,
         0.1 ,  0.07, -0.13, -0.03,  0.31, -0.42]])

In [37]:
y_pred = model.predict(x)

In [38]:
y_pred

array([0, 0, 0, ..., 1, 0, 0], dtype=int64)

In [40]:
y_pred_df=pd.DataFrame({"actual":y,"predicted_values":model.predict(x)})

In [41]:
y_pred_df

actual  predicted_values
0           0                 0
1           0                 0
2           0                 0
3           0                 0
4           0                 0
...       ...               ...
45206       1                 1
45207       1                 0
45208       1                 1
45209       0                 0
45210       0                 0

[45211 rows x 2 columns]

In [42]:
y_pred_df["actual"].value_counts()

0    39922
1     5289
Name: actual, dtype: int64

In [43]:
y_pred_df["predicted_values"].value_counts()

0    43244
1     1967
Name: predicted_values, dtype: int64

In [44]:
#confusion matrix for model building
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score as  ac
confusion_matrix=confusion_matrix(y,y_pred)

In [45]:
print(confusion_matrix)

[[39137   785]
 [ 4107  1182]]


In [46]:
ac(y,y_pred)

0.8917962442768352

In [47]:
#confusion model is 89% accurate

In [48]:
#classification reports
print(classification_report(y,y_pred))

              precision    recall  f1-score   support

           0       0.91      0.98      0.94     39922
           1       0.60      0.22      0.33      5289

    accuracy                           0.89     45211
   macro avg       0.75      0.60      0.63     45211
weighted avg       0.87      0.89      0.87     45211



In [49]:
#train test prediction


In [53]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=12)
model=LogisticRegression()
model.fit(x_train,y_train)
y_pred = model.predict(x_test)

In [54]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.91      0.98      0.94     11990
           1       0.60      0.23      0.33      1574

    accuracy                           0.89     13564
   macro avg       0.75      0.60      0.64     13564
weighted avg       0.87      0.89      0.87     13564



In [55]:
from sklearn.tree import DecisionTreeClassifier
from sklearn import tree

In [56]:
model=DecisionTreeClassifier(criterion="gini",min_samples_split=5,max_depth=10)
model.fit(x_train,y_train)

DecisionTreeClassifier(max_depth=10, min_samples_split=5)

In [57]:
y_pred=model.predict(x_test)

In [58]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.93      0.96      0.94     11990
           1       0.60      0.41      0.49      1574

    accuracy                           0.90     13564
   macro avg       0.76      0.69      0.72     13564
weighted avg       0.89      0.90      0.89     13564

